# Generated by Django 6.0.3 on 2026-03-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0013_alter_city_alternate_names_alter_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_status', models.CharField(max_length=50, verbose_name='Clima (Estado principal)')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción detallada')),
                ('icon_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código de icono')),
                ('temperature', models.FloatField(verbose_name='Temperatura (°C)')),
                ('feels_like', models.FloatField(verbose_name='Sensación térmica (°C)')),
                ('temp_min', models.FloatField(blank=True, null=True, verbose_name='Temperatura mínima (°C)')),
                ('temp_max', models.FloatField(blank=True, null=True, verbose_name='Temperatura máxima (°C)')),
                ('pressure', models.IntegerField(blank=True, null=True, verbose_name='Presión (hPa)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='Humedad (%)')),
                ('visibility', models.IntegerField(blank=True, null=True, verbose_name='Visibilidad (m)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='Velocidad del viento (m/s)')),
                ('wind_deg', models.IntegerField(blank=True, null=True, verbose_name='Dirección del viento (grados)')),
                ('wind_gust', models.FloatField(blank=True, null=True, verbose_name='Ráfagas de viento (m/s)')),
                ('clouds_all', models.IntegerField(blank=True, null=True, verbose_name='Nubosidad (%)')),
                ('rain_1h', models.FloatField(blank=True, null=True, verbose_name='Lluvia (última hora)')),
                ('snow_1h', models.FloatField(blank=True, null=True, verbose_name='Nieve (última hora)')),
                ('timestamp', models.DateTimeField(verbose_name='Momento de la medición')),
                ('sunrise', models.DateTimeField(blank=True, null=True, verbose_name='Amanecer')),
                ('sunset', models.DateTimeField(blank=True, null=True, verbose_name='Atardecer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_history', to='cities_light.city', verbose_name='Ciudad')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_history', to='cities_light.country', verbose_name='País')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_history', to='cities_light.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Contexto climático',
                'verbose_name_plural': 'Contextos climáticos',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='context_wea_timesta_b6806b_idx'), models.Index(fields=['city'], name='context_wea_city_id_808bb1_idx'), models.Index(fields=['region'], name='context_wea_region__c982f0_idx')],
            },
        ),
    ]
