# Generated by Django 6.0.3 on 2026-03-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathercontext',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Contexto climático', 'verbose_name_plural': 'Contextos climáticos'},
        ),
        migrations.AlterField(
            model_name='weathercontext',
            name='icon_code',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Código de icono'),
        ),
    ]
