# Generated by Django 4.2.29 on 2026-03-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0002_alter_weathercontext_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weathercontext",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Weather Context",
                "verbose_name_plural": "Weather Contexts",
            },
        ),
    ]
