# Generated by Django 6.0.3 on 2026-04-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_alter_weathercontext_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathercontext',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Weather Context', 'verbose_name_plural': 'Weather Contexts'},
        ),
    ]
