# Generated by Django 4.2.x on 2026-04-14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("context", "0003_alter_weathercontext_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Title")),
                (
                    "source",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="Source"),
                ),
                (
                    "url",
                    models.URLField(max_length=600, unique=True, verbose_name="URL"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, default="", verbose_name="Summary"),
                ),
                (
                    "language",
                    models.CharField(default="en", max_length=10, verbose_name="Language"),
                ),
                (
                    "category",
                    models.CharField(blank=True, default="general", max_length=80, verbose_name="Category"),
                ),
                (
                    "sentiment_score",
                    models.FloatField(default=0.0, verbose_name="Sentiment score"),
                ),
                (
                    "sentiment_label",
                    models.CharField(default="neutral", max_length=20, verbose_name="Sentiment label"),
                ),
                (
                    "is_breaking",
                    models.BooleanField(default=False, verbose_name="Breaking"),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Published at"),
                ),
                (
                    "fetched_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fetched at"),
                ),
            ],
            options={
                "verbose_name": "News Context",
                "verbose_name_plural": "News Contexts",
                "ordering": ("-published_at", "-fetched_at"),
            },
        ),
        migrations.AddIndex(
            model_name="newscontext",
            index=models.Index(fields=["-published_at"], name="context_new_publish_184b2f_idx"),
        ),
        migrations.AddIndex(
            model_name="newscontext",
            index=models.Index(fields=["source"], name="context_new_source_b8532b_idx"),
        ),
        migrations.AddIndex(
            model_name="newscontext",
            index=models.Index(fields=["category"], name="context_new_categor_0498df_idx"),
        ),
        migrations.AddIndex(
            model_name="newscontext",
            index=models.Index(fields=["sentiment_label"], name="context_new_sentime_9e79c5_idx"),
        ),
    ]
