"""
Schemas para API de Interactions usando Django-Ninja.
"""

from typing import List, Literal, Optional

from ninja import Schema
from pydantic import Field


class InteractionCreateSchema(Schema):
    """
    Schema para crear una nueva interacción.
    """

    track_id: int
    feedback: str  # 'completed', 'skip', 'skip_immediate', 'replay', 'added_to_playlist'
    play_duration: int = 0
    track_duration: int = 0
    session_id: str = ""
    weather_id: Optional[int] = None
    news_ids: Optional[List[int]] = None
    playlist_id: str = ""


class InteractionResponseSchema(Schema):
    """
    Schema para responder con una interacción.
    """

    id: int
    user_id: int
    track_id: int
    feedback: str
    reward: float
    completion_percentage: float
    is_positive: bool
    started_at: str
    created_at: str


class SessionStatsSchema(Schema):
    """
    Schema con estadísticas de una sesión.
    """

    session_id: str
    total_tracks: int
    skip_count: int
    completed_count: int
    average_reward: float
    total_reward: float
    skip_rate: float
    completion_rate: float
    started_at: str
    is_active: bool


class UserStatsSchema(Schema):
    """
    Schema con estadísticas del usuario.
    """

    user_id: int
    total_interactions: int
    total_skips: int
    total_completed: int
    average_reward: float
    total_reward: float
    skip_rate: float
    completion_rate: float
    favorite_genres: List[str]
    favorite_artists: List[str]
    average_session_length: float


class PlaylistGenerateSchema(Schema):
    """
    Schema para solicitar generación de playlist.
    """

    name: str = "Generated by Moodsic"
    count: int = 10  # Número de canciones
    weather_id: Optional[int] = None
    use_context: bool = True
    news_category: Literal[
        "general",
        "music",
        "markets",
        "sports",
        "politics",
    ] = "general"
    news_query: Optional[str] = None
    news_limit: int = Field(20, ge=1, le=50)


class PlaylistGenerateResponseSchema(Schema):
    """
    Schema de respuesta para playlist generada.
    """

    playlist_id: str
    playlist_name: str
    tracks_count: int
    session_id: str
    track_ids: List[int]
    track_names: List[str]
    estimated_duration: int  # En segundos
    created_at: str


class DashboardMetricsSchema(Schema):
    """
    Schema con métricas del dashboard.
    """

    total_users: int
    total_interactions: int
    average_skip_rate: float
    average_completion_rate: float
    total_reward_generated: float
    active_sessions: int
    top_tracks: List[dict]
    user_growth: List[dict]
