[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

cache_dir = .pytest_cache

addopts =
    --cov=apps
    --cov=tests
    --cov-config=.coveragerc
    --cov-report=term-missing:skip-covered
    --cov-fail-under=93
;    --disable-warnings
    --strict-markers
    -q

# Markers personalizados
markers =
    unit: Tests unitarios (dominio puro)
    integration: Tests de integración (con BD)
    slow: Tests que tardan mucho

# Manejo de advertencias
filterwarnings =
    ignore::DeprecationWarning

# Django
django_find_project = true
