# Generated by Django 6.0.3 on 2026-03-03 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True, verbose_name='Spotify ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('popularity', models.IntegerField(blank=True, null=True, verbose_name='Popularidad')),
                ('genres', models.JSONField(blank=True, default=list, verbose_name='Géneros')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Imágenes')),
                ('uri', models.CharField(blank=True, default='', max_length=255, verbose_name='URI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True, verbose_name='Spotify ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('album_type', models.CharField(blank=True, default='', max_length=50, verbose_name='Tipo de álbum')),
                ('total_tracks', models.IntegerField(blank=True, null=True, verbose_name='Total de canciones')),
                ('release_date', models.CharField(blank=True, default='', max_length=50, verbose_name='Fecha de lanzamiento')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Imágenes')),
                ('uri', models.CharField(blank=True, default='', max_length=255, verbose_name='URI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artists', models.ManyToManyField(related_name='albums', to='music.artist', verbose_name='Artistas')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbumes',
                'ordering': ('-release_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True, verbose_name='Spotify ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_public', models.BooleanField(default=True, verbose_name='Es pública')),
                ('snapshot_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Snapshot ID')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Imágenes')),
                ('uri', models.CharField(blank=True, default='', max_length=255, verbose_name='URI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Lista de reproducción',
                'verbose_name_plural': 'Listas de reproducción',
                'ordering': ('-updated_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True, verbose_name='Spotify ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('duration_ms', models.IntegerField(verbose_name='Duración (ms)')),
                ('explicit', models.BooleanField(default=False, verbose_name='Explícito')),
                ('popularity', models.IntegerField(blank=True, null=True, verbose_name='Popularidad')),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de previsualización')),
                ('track_number', models.IntegerField(verbose_name='Número de pista')),
                ('uri', models.CharField(blank=True, default='', max_length=255, verbose_name='URI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='Álbum')),
                ('artists', models.ManyToManyField(related_name='tracks', to='music.artist', verbose_name='Artistas')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(blank=True, null=True, verbose_name='Añadida en')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist', verbose_name='Lista de reproducción')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track', verbose_name='Canción')),
            ],
            options={
                'verbose_name': 'Canción de la lista',
                'verbose_name_plural': 'Canciones de la lista',
                'ordering': ('playlist', 'order'),
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='music.PlaylistTrack', to='music.track', verbose_name='Canciones'),
        ),
        migrations.CreateModel(
            name='TrackAudioFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('danceability', models.FloatField(verbose_name='Danceability')),
                ('energy', models.FloatField(verbose_name='Energy')),
                ('key', models.IntegerField(verbose_name='Key')),
                ('loudness', models.FloatField(verbose_name='Loudness')),
                ('mode', models.IntegerField(verbose_name='Mode')),
                ('speechiness', models.FloatField(verbose_name='Speechiness')),
                ('acousticness', models.FloatField(verbose_name='Acousticness')),
                ('instrumentalness', models.FloatField(verbose_name='Instrumentalness')),
                ('liveness', models.FloatField(verbose_name='Liveness')),
                ('valence', models.FloatField(verbose_name='Valence')),
                ('tempo', models.FloatField(verbose_name='Tempo')),
                ('time_signature', models.IntegerField(verbose_name='Time Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_features', to='music.track', verbose_name='Canción')),
            ],
            options={
                'verbose_name': 'Características de audio',
                'verbose_name_plural': 'Características de audio',
            },
        ),
    ]
