# Generated by Django 4.2.29 on 2026-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="preview_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="URL de previsualización"
            ),
        ),
    ]
