# Generated by Django 6.0.4 on 2026-05-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_alter_track_preview_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="analysis_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="URL de análisis"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="genre",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Género"
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="is_playable",
            field=models.BooleanField(default=True, verbose_name="Reproducible"),
        ),
        migrations.AddField(
            model_name="track",
            name="subgenre",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Subgénero"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlists",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.CreateModel(
            name="PlaylistGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=100, verbose_name="Género")),
                (
                    "subgenre",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Subgénero"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genres",
                        to="music.playlist",
                        verbose_name="Playlist",
                    ),
                ),
            ],
            options={
                "verbose_name": "Género de playlist",
                "verbose_name_plural": "Géneros de playlists",
                "unique_together": {("playlist", "genre")},
            },
        ),
        migrations.CreateModel(
            name="TrackLyrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist_name",
                    models.CharField(max_length=255, verbose_name="Artista (CSV)"),
                ),
                (
                    "song_name",
                    models.CharField(max_length=255, verbose_name="Canción (CSV)"),
                ),
                ("text", models.TextField(verbose_name="Letra")),
                (
                    "language",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Idioma"
                    ),
                ),
                (
                    "word_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Número de palabras"
                    ),
                ),
                (
                    "match_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Score de coincidencia"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        default="unmatched",
                        max_length=20,
                        verbose_name="Estado de coincidencia",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="mill-song-data", max_length=50, verbose_name="Fuente"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lyrics",
                        to="music.track",
                        verbose_name="Canción",
                    ),
                ),
            ],
            options={
                "verbose_name": "Letra de canción",
                "verbose_name_plural": "Letras de canciones",
                "indexes": [
                    models.Index(
                        fields=["match_status"], name="music_track_match_s_082da9_idx"
                    ),
                    models.Index(
                        fields=["track"], name="music_track_track_i_521a5a_idx"
                    ),
                ],
            },
        ),
    ]
