# Generated by Django 6.0.4 on 2026-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_track_analysis_url_track_genre_track_is_playable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracklyrics",
            name="sentiment_label",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Sentiment label"
            ),
        ),
        migrations.AddField(
            model_name="tracklyrics",
            name="sentiment_neg",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Negativity score"
            ),
        ),
        migrations.AddField(
            model_name="tracklyrics",
            name="sentiment_neu",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Neutrality score"
            ),
        ),
        migrations.AddField(
            model_name="tracklyrics",
            name="sentiment_pos",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Positivity score"
            ),
        ),
        migrations.AddField(
            model_name="tracklyrics",
            name="sentiment_score",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Sentiment compound"
            ),
        ),
    ]
