# Generated by Django 4.2.29 on 2026-03-25 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music", "0002_alter_track_preview_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="ID de sesión"
                    ),
                ),
                (
                    "weather_id",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="ID Contexto al inicio de sesión",
                    ),
                ),
                (
                    "total_tracks",
                    models.IntegerField(
                        default=0, verbose_name="Total de canciones reproducidas"
                    ),
                ),
                (
                    "skip_count",
                    models.IntegerField(default=0, verbose_name="Total de skips"),
                ),
                (
                    "completed_count",
                    models.IntegerField(
                        default=0, verbose_name="Total de canciones completadas"
                    ),
                ),
                (
                    "average_reward",
                    models.FloatField(
                        default=0.0, verbose_name="Reward promedio de la sesión"
                    ),
                ),
                (
                    "total_reward",
                    models.FloatField(
                        default=0.0, verbose_name="Reward total de la sesión"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Inicio de sesión"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fin de sesión"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="¿Sesión activa?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de interacción",
                "verbose_name_plural": "Sesiones de interacción",
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="interaction_user_id_9ee3a2_idx",
                    ),
                    models.Index(
                        fields=["session_id"], name="interaction_session_6758f6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback",
                    models.CharField(
                        choices=[
                            ("completed", "Canción completada"),
                            ("skip", "Salto normal"),
                            ("skip_immediate", "Salto inmediato (< 5 seg)"),
                            ("replay", "Reproducida de nuevo"),
                            ("added_to_playlist", "Añadida a playlist"),
                        ],
                        default="completed",
                        max_length=20,
                        verbose_name="Tipo de feedback",
                    ),
                ),
                (
                    "weather_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID Contexto climático"
                    ),
                ),
                (
                    "news_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="IDs de noticias"
                    ),
                ),
                (
                    "reward",
                    models.FloatField(default=0.0, verbose_name="Recompensa calculada"),
                ),
                (
                    "play_duration",
                    models.IntegerField(
                        default=0,
                        help_text="Cuántos segundos del track se reprodujeron",
                        verbose_name="Duración reproducida (segundos)",
                    ),
                ),
                (
                    "track_duration",
                    models.IntegerField(
                        default=0, verbose_name="Duración total del track (segundos)"
                    ),
                ),
                (
                    "completion_percentage",
                    models.FloatField(
                        default=0.0, verbose_name="Porcentaje completado (%)"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Para agrupar interacciones de una sesión",
                        max_length=255,
                        verbose_name="ID de sesión",
                    ),
                ),
                (
                    "playlist_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID de playlist (Spotify)",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hora de inicio"
                    ),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hora de término"
                    ),
                ),
                (
                    "is_positive",
                    models.BooleanField(
                        default=True,
                        help_text="True si feedback != 'skip'",
                        verbose_name="¿Es feedback positivo?",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="music.track",
                        verbose_name="Canción",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interacción",
                "verbose_name_plural": "Interacciones",
                "ordering": ("-started_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "-started_at"],
                        name="interaction_user_id_2c77f8_idx",
                    ),
                    models.Index(
                        fields=["track", "-started_at"],
                        name="interaction_track_i_580c37_idx",
                    ),
                    models.Index(
                        fields=["feedback"], name="interaction_feedbac_77f9e5_idx"
                    ),
                    models.Index(
                        fields=["session_id"], name="interaction_session_40851a_idx"
                    ),
                ],
            },
        ),
    ]
