"""
Servicio de Generación de Playlists usando el Agente RL.
"""

import logging
import uuid
from collections import Counter

from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models import Avg, Sum
from django.utils import timezone

from apps.context.models import NewsContext, WeatherContext
from apps.context.services.news_service import NewsService
from apps.interactions.services.reward_service import get_reward_service
from apps.music.models import Album, Artist, Playlist, PlaylistTrack, Track
from apps.music.services.spotify_music_service import SpotifyMusicService
from ml.agent import get_agent
from ml.state_builder import get_state_builder

logger = logging.getLogger(__name__)

User = get_user_model()

ALLOWED_NEWS_CATEGORIES = {
    "general",
    "music",
    "markets",
    "sports",
    "politics",
}

DEFAULT_NEWS_QUERIES = {
    "general": "world OR society OR culture",
    "music": "music OR entertainment OR artists",
    "markets": "stock market OR economy OR inflation",
    "sports": "sports OR football OR basketball",
    "politics": "politics OR government OR election",
}


class PlaylistGenerationService:
    """
    Servicio para generar playlists inteligentes usando el agente RL.

    Coordina:
    1. Construcción del estado (contexto actual)
    2. Selección de tracks usando el agente
    3. Creación de playlist en Spotify
    4. Registro de la sesión para entrenamiento
    """

    def __init__(self):
        """Inicializa el servicio."""
        self.agent = get_agent()
        self.reward_service = get_reward_service()
        self.state_builder = get_state_builder()
        self.context_weight, self.history_weight = self._get_scoring_weights()

    def generate_playlist(
        self,
        user: User,
        playlist_name: str = "Generated by Moodsic",
        count: int = 10,
        weather_context: dict | None = None,
        use_context: bool = True,
        news_category: str = "general",
        news_query: str | None = None,
        news_limit: int = 20,
    ) -> dict:
        """
        Genera una playlist personalizada para el usuario.

        Args:
            user: Usuario para el que generar la playlist
            playlist_name: Nombre de la playlist
            count: Número de canciones a incluir
            weather_context: Diccionario con contexto climático
            use_context: Si usar el contexto en la generación

        Returns:
            Dict con información de la playlist generada
        """
        logger.info(
            f"Generando playlist para usuario {user.username} con {count} canciones"
        )

        try:
            # Crear sesión única
            session_id = str(uuid.uuid4())

            # Obtener tracks disponibles y registrar su procedencia
            available_tracks, source_meta = self._get_available_tracks_with_meta(user)
            generation_meta = {
                "used_spotify_sync": False,
                "used_cached_news": False,
                "used_local_catalog": source_meta["used_local_catalog"],
                "used_spotify_catalog_fallback": source_meta[
                    "used_spotify_catalog_fallback"
                ],
            }

            if len(available_tracks) == 0:
                raise ValueError("No hay canciones disponibles para generar playlist")

            # Limitar a tracks disponibles
            count = min(count, len(available_tracks))

            user_history = self._get_user_history(user)
            track_scores = self._score_tracks(
                available_tracks,
                weather_context=weather_context,
                user_history=user_history,
            )
            available_actions = sorted(
                range(len(available_tracks)),
                key=lambda idx: track_scores[idx],
                reverse=True,
            )

            # Construir estado inicial
            news_category = self._normalize_news_category(news_category)
            effective_query = (news_query or "").strip() or DEFAULT_NEWS_QUERIES[
                news_category
            ]

            if effective_query:
                try:
                    _, news_meta = NewsService.fetch_and_store_news(
                        query=effective_query,
                        category=news_category,
                        page_size=max(5, min(news_limit, 50)),
                        return_meta=True,
                    )
                    generation_meta["used_cached_news"] = bool(
                        news_meta.get("used_cached_news", False)
                    )
                except Exception as exc:
                    generation_meta["used_cached_news"] = True
                    logger.warning(
                        f"No se pudo refrescar noticias para query '{effective_query}': {exc}"
                    )

            news_contexts = self._get_latest_news_contexts(
                category=news_category,
                limit=news_limit,
            )
            state = self.state_builder.build_state(
                user=user,
                weather_context=weather_context,
                current_track=None,
                time_of_day=self._get_time_of_day(),
                news_contexts=news_contexts,
            )

            # Seleccionar tracks usando el agente
            selected_track_indices = []

            for _step in range(count):
                # El agente selecciona la mejor acción (track)
                action = self.agent.select_action(
                    state,
                    available_actions=available_actions,
                    training=False,  # Usar explotación pura
                )

                track_idx = action
                selected_track_indices.append(track_idx)

                # Remover track seleccionado para no repetir
                available_actions.remove(action)

                # Actualizar estado para siguiente iteración
                track = available_tracks[track_idx]
                track_features = self._get_track_audio_features(track)

                state = self.state_builder.build_state(
                    user=user,
                    weather_context=weather_context,
                    current_track=track_features,
                    time_of_day=self._get_time_of_day(),
                    news_contexts=news_contexts,
                )

            # Crear playlist en BD
            selected_tracks = [available_tracks[idx] for idx in selected_track_indices]
            playlist = self._create_playlist(
                user=user,
                playlist_name=playlist_name,
                tracks=selected_tracks,
                session_id=session_id,
            )

            # Sincronizar con Spotify si el usuario está conectado
            if user.is_spotify_connected:
                try:
                    spotify_playlist = self._sync_playlist_to_spotify(
                        user=user,
                        playlist=playlist,
                        tracks=selected_tracks,
                    )
                    if spotify_playlist:
                        playlist.spotify_id = spotify_playlist.get(
                            "id", f"moodsic_{session_id}"
                        )
                        playlist.uri = spotify_playlist.get("uri", "")
                        playlist.save()
                        generation_meta["used_spotify_sync"] = True
                        logger.info(
                            f"Playlist sincronizada con Spotify: {spotify_playlist.get('id')}"
                        )
                except Exception as e:
                    logger.warning(f"No se pudo sincronizar con Spotify: {e}")
                    # Continuar sin Spotify, playlist sigue siendo válida localmente

            logger.info(
                f"Playlist creada exitosamente: {playlist.id} "
                f"con {len(selected_tracks)} canciones"
            )

            return {
                "playlist_id": playlist.spotify_id,
                "playlist_name": playlist.name,
                "tracks_count": len(selected_tracks),
                "track_ids": [t.id for t in selected_tracks],
                "track_names": [t.name for t in selected_tracks],
                "estimated_duration": sum(t.duration_ms for t in selected_tracks)
                // 1000,
                "session_id": session_id,
                "created_at": timezone.now().isoformat(),
                "mode": self._resolve_generation_mode(generation_meta),
                "used_spotify_sync": generation_meta["used_spotify_sync"],
                "used_cached_news": generation_meta["used_cached_news"],
                "used_local_catalog": generation_meta["used_local_catalog"],
                "used_spotify_catalog_fallback": generation_meta[
                    "used_spotify_catalog_fallback"
                ],
            }

        except Exception as e:
            logger.error(f"Error generando playlist: {e}", exc_info=True)
            raise

    def record_interaction(
        self,
        user: User,
        track: Track,
        feedback: str,
        play_duration: int,
        track_duration: int,
        session_id: str,
        weather_id: int | None = None,
        news_ids: list[int] | None = None,
    ) -> dict:
        """
        Registra la interacción del usuario con un track.

        Args:
            user: Usuario
            track: Track reproducido
            feedback: Tipo de feedback
            play_duration: Segundos reproducidos
            track_duration: Duración total del track
            session_id: ID de la sesión
            weather_id: ID del contexto climático
            news_ids: IDs de noticias

        Returns:
            Dict con información de la interacción registrada
        """
        from apps.interactions.models import Interaction

        logger.info(
            f"Registrando interacción: {user.username} - {track.name} ({feedback})"
        )

        try:
            # Obtener contexto para calcular reward
            weather_context = None
            if weather_id:
                try:
                    weather = WeatherContext.objects.get(id=weather_id)
                    weather_context = {
                        "temperature": weather.temperature,
                        "humidity": weather.humidity,
                        "wind_speed": weather.wind_speed,
                        "main_status": weather.main_status,
                    }
                except WeatherContext.DoesNotExist:
                    pass

            # Obtener audio features del track
            audio_features = self._get_track_audio_features(track)

            # Obtener historico del usuario
            user_history = self._get_user_history(user)

            # Calcular reward desde la capa de dominio de interactions
            reward = self.reward_service.calculate_interaction_reward(
                user_feedback=feedback,
                user=user,
                track=track,
                weather_id=weather_id,
                news_ids=news_ids,
                user_history=user_history,
            )

            # Guardar interacción
            interaction = Interaction.objects.create(
                user=user,
                track=track,
                feedback=feedback,
                play_duration=play_duration,
                track_duration=track_duration,
                reward=reward,
                weather_id=weather_id,
                news_ids=news_ids or [],
                session_id=session_id,
            )

            # Guardar la experiencia en el replay buffer del agente para entrenamient futuro
            news_contexts = []
            if news_ids:
                news_contexts = [
                    {
                        "sentiment_score": n.sentiment_score,
                        "sentiment_label": n.sentiment_label,
                        "is_breaking": n.is_breaking,
                    }
                    for n in NewsContext.objects.filter(id__in=news_ids)
                ]

            self.state_builder.build_state(
                user,
                weather_context,
                audio_features,
                news_contexts=news_contexts,
            )
            # Aquí iría la acción (track index) pero se omite para no complicar

            logger.info(f"Interacción guardada: {interaction.id}, Reward: {reward}")

            return {
                "interaction_id": interaction.id,
                "reward": reward,
                "completion_percentage": interaction.completion_percentage,
                "is_positive": interaction.is_positive,
            }

        except Exception as e:
            logger.error(f"Error registrando interacción: {e}", exc_info=True)
            raise

    def get_user_stats(self, user: User) -> dict:
        """
        Obtiene estadísticas del usuario.
        """
        from apps.interactions.models import Interaction

        interactions = Interaction.objects.filter(user=user)
        total = interactions.count()

        if total == 0:
            return {
                "user_id": user.id,
                "total_interactions": 0,
                "total_skips": 0,
                "total_completed": 0,
                "average_reward": 0.0,
                "total_reward": 0.0,
                "skip_rate": 0.0,
                "completion_rate": 0.0,
                "favorite_genres": [],
                "favorite_artists": [],
                "average_session_length": 0.0,
            }

        skips = interactions.filter(feedback__startswith="skip").count()
        completed = interactions.filter(feedback="completed").count()
        avg_reward = interactions.aggregate(avg=Avg("reward"))["avg"] or 0.0
        total_reward = interactions.aggregate(total=Sum("reward"))["total"] or 0.0

        stats = {
            "user_id": user.id,
            "total_interactions": total,
            "total_skips": skips,
            "total_completed": completed,
            "average_reward": float(avg_reward),
            "total_reward": float(total_reward),
            "skip_rate": skips / total if total > 0 else 0.0,
            "completion_rate": completed / total if total > 0 else 0.0,
        }

        stats["favorite_genres"] = self.get_user_favorite_genres(user)
        stats["favorite_artists"] = self.get_user_favorite_artists(user)
        stats["average_session_length"] = self.get_average_session_length(user)
        return stats

    def _get_available_tracks(self, user: User, limit: int = 500) -> list[Track]:
        tracks, _meta = self._get_available_tracks_with_meta(user, limit=limit)
        return tracks

    def _get_available_tracks_with_meta(
        self, user: User, limit: int = 500
    ) -> tuple[list[Track], dict[str, bool]]:
        """
        Obtiene tracks disponibles para seleccionar y registra su procedencia.
        """
        max_tracks = min(limit, self.agent.action_dim)
        local_tracks = list(
            Track.objects.prefetch_related("artists").all()[:max_tracks]
        )
        if local_tracks:
            return local_tracks, {
                "used_local_catalog": True,
                "used_spotify_catalog_fallback": False,
            }

        hydrated_tracks = self._hydrate_tracks_from_spotify(user, limit=max_tracks)
        if hydrated_tracks:
            return hydrated_tracks[:max_tracks], {
                "used_local_catalog": False,
                "used_spotify_catalog_fallback": True,
            }

        return [], {
            "used_local_catalog": False,
            "used_spotify_catalog_fallback": False,
        }

    def _hydrate_tracks_from_spotify(self, user: User, limit: int = 100) -> list[Track]:
        """Populate the local catalog from Spotify as an online fallback."""
        if not getattr(user, "is_spotify_connected", False):
            return []

        try:
            spotify_service = SpotifyMusicService(user)
            if not spotify_service.client:
                return []

            # Combine liked tracks and top tracks for more variety
            half_limit = limit // 2
            liked_raw = spotify_service.get_user_liked_tracks(limit=half_limit) or []
            liked_tracks = [item["track"] for item in liked_raw if "track" in item]

            top_tracks = (
                spotify_service.get_top_tracks(limit=limit - len(liked_tracks)) or []
            )

            tracks_data = liked_tracks + top_tracks

            if not tracks_data:
                logger.info("No tracks found on Spotify for hydration.")
                return []

            imported_tracks = self._upsert_spotify_tracks(tracks_data)
            if imported_tracks:
                logger.info(
                    f"Imported {len(imported_tracks)} tracks from Spotify for fallback hydration"
                )
            return imported_tracks
        except Exception as exc:
            logger.warning(f"Could not hydrate tracks from Spotify: {exc}")
            return []

    @staticmethod
    def _upsert_spotify_tracks(tracks_data: list[dict]) -> list[Track]:
        imported_tracks: list[Track] = []

        for index, item in enumerate(tracks_data):
            spotify_id = (item.get("id") or "").strip()
            name = (item.get("name") or f"Remote Track {index + 1}").strip()
            if not spotify_id:
                continue

            album_data = item.get("album")
            if isinstance(album_data, dict):
                album_name = album_data.get("name", "Unknown Album")
                album_spotify_id = album_data.get("id", f"album_{spotify_id}")
            else:
                album_name = str(album_data or "Unknown Album")
                album_spotify_id = f"album_{spotify_id}"

            album, _ = Album.objects.get_or_create(
                spotify_id=album_spotify_id,
                defaults={"name": album_name},
            )

            track, _ = Track.objects.update_or_create(
                spotify_id=spotify_id,
                defaults={
                    "name": name,
                    "album": album,
                    "duration_ms": int(item.get("duration_ms") or 180000),
                    "explicit": bool(item.get("explicit", False)),
                    "track_number": int(item.get("track_number") or 1),
                    "popularity": int(item.get("popularity") or 50),
                    "uri": item.get("uri") or f"spotify:track:{spotify_id}",
                    "preview_url": item.get("preview_url") or "",
                },
            )

            track.artists.clear()
            for artist_idx, artist_data in enumerate(item.get("artists", [])):
                if isinstance(artist_data, dict):
                    artist_name = (
                        artist_data.get("name") or f"Artist {artist_idx + 1}"
                    ).strip()
                    artist_spotify_id = (
                        artist_data.get("id") or f"artist_{spotify_id}_{artist_idx}"
                    )
                else:
                    artist_name = str(artist_data).strip() or f"Artist {artist_idx + 1}"
                    artist_spotify_id = f"artist_{spotify_id}_{artist_idx}"

                artist, _ = Artist.objects.get_or_create(
                    spotify_id=artist_spotify_id,
                    defaults={"name": artist_name},
                )
                track.artists.add(artist)

            imported_tracks.append(track)

        return imported_tracks

    def _get_time_of_day(self) -> str:
        """Obtiene la hora del día actual."""
        hour = timezone.now().hour
        if 6 <= hour < 12:
            return "morning"
        elif 12 <= hour < 18:
            return "afternoon"
        elif 18 <= hour <= 23:
            return "evening"
        else:
            return "night"

    @staticmethod
    def _get_track_audio_features(track: Track) -> dict:
        """
        Obtiene las características de audio de un track.
        """
        try:
            if hasattr(track, "audio_features"):
                af = track.audio_features
                return {
                    "energy": af.energy,
                    "danceability": af.danceability,
                    "valence": af.valence,
                    "acousticness": af.acousticness,
                    "instrumentalness": af.instrumentalness,
                    "liveness": af.liveness,
                    "loudness": af.loudness,
                    "tempo": af.tempo,
                    "speechiness": af.speechiness,
                    "key": af.key,
                    "mode": af.mode,
                    "time_signature": af.time_signature,
                }
        except Exception:
            pass

        # Retornar defaults si no existen
        return {
            "energy": 0.5,
            "danceability": 0.5,
            "valence": 0.5,
            "acousticness": 0.3,
            "instrumentalness": 0.0,
            "liveness": 0.2,
            "loudness": -5,
            "tempo": 120,
            "speechiness": 0.0,
            "key": 0,
            "mode": 1,
            "time_signature": 4,
        }

    def _get_user_history(self, user: User) -> dict:
        """
        Obtiene el historico del usuario incluyendo preferencias.
        """
        from apps.interactions.models import Interaction

        interactions = (
            Interaction.objects.filter(user=user)
            .select_related("track__audio_features")
            .prefetch_related("track__artists")
        )

        if interactions.count() == 0:
            return {
                "skip_rate": 0.3,
                "completion_rate": 0.7,
                "avg_energy": 0.5,
                "avg_danceability": 0.5,
                "avg_valence": 0.5,
                "favorite_artists": [],
                "favorite_genres": [],
            }

        skips = interactions.filter(feedback__startswith="skip").count()
        total = interactions.count()
        avg_energy = 0.0
        avg_danceability = 0.0
        avg_valence = 0.0
        feature_count = 0

        for interaction in interactions:
            audio_features = getattr(interaction.track, "audio_features", None)
            if audio_features:
                avg_energy += audio_features.energy
                avg_danceability += audio_features.danceability
                avg_valence += audio_features.valence
                feature_count += 1

        if feature_count > 0:
            avg_energy /= feature_count
            avg_danceability /= feature_count
            avg_valence /= feature_count
        else:
            avg_energy = 0.5
            avg_danceability = 0.5
            avg_valence = 0.5

        preferences = self._get_user_preferences(user)

        return {
            "skip_rate": skips / total if total > 0 else 0.0,
            "completion_rate": 1 - (skips / total if total > 0 else 0.0),
            "avg_energy": avg_energy,
            "avg_danceability": avg_danceability,
            "avg_valence": avg_valence,
            "favorite_artists": preferences["artists"],
            "favorite_genres": preferences["genres"],
        }

    def _get_user_preferences(self, user: User) -> dict[str, list[str]]:
        """
        Retorna los artistas y géneros más frecuentes en el historial del usuario.
        """
        from apps.interactions.models import Interaction

        interactions = (
            Interaction.objects.filter(user=user)
            .select_related("track__audio_features")
            .prefetch_related("track__artists")
        )

        artist_counter = Counter()
        genre_counter = Counter()

        for interaction in interactions:
            for artist in interaction.track.artists.all():
                artist_counter[artist.name] += 1
                for genre in getattr(artist, "genres", []) or []:
                    normalized = genre.strip()
                    if normalized:
                        genre_counter[normalized] += 1

        return {
            "artists": [name for name, _ in artist_counter.most_common(5)],
            "genres": [name for name, _ in genre_counter.most_common(5)],
        }

    @staticmethod
    def _get_scoring_weights() -> tuple[float, float]:
        """Return normalized recommender weights.

        The benchmark winner is used as the default balance: 0.6 for current
        context fit and 0.4 for user history/personalization.
        """
        context_weight = float(getattr(settings, "RECOMMENDER_CONTEXT_WEIGHT", 0.6))
        history_weight = float(getattr(settings, "RECOMMENDER_HISTORY_WEIGHT", 0.4))

        context_weight = max(0.0, context_weight)
        history_weight = max(0.0, history_weight)
        total = context_weight + history_weight
        if total <= 0:
            return 0.6, 0.4
        return context_weight / total, history_weight / total

    def _score_tracks(
        self,
        tracks: list[Track],
        weather_context: dict | None = None,
        user_history: dict | None = None,
    ) -> list[float]:
        """
        Calcula una puntuación para cada track basada en clima e historial.
        """
        user_history = user_history or {}
        return [
            self._score_track(track, weather_context, user_history) for track in tracks
        ]

    @staticmethod
    def _get_latest_news_contexts(
        category: str = "general", limit: int = 20
    ) -> list[dict]:
        """Return compact latest news context used by the state builder."""
        queryset = NewsContext.objects.order_by("-published_at")
        if category and category != "all":
            queryset = queryset.filter(category=category)
        news_items = queryset[: max(1, min(limit, 50))]
        return [
            {
                "sentiment_score": item.sentiment_score,
                "sentiment_label": item.sentiment_label,
                "is_breaking": item.is_breaking,
            }
            for item in news_items
        ]

    @staticmethod
    def _normalize_news_category(category: str) -> str:
        normalized = (category or "general").strip().lower()
        if normalized not in ALLOWED_NEWS_CATEGORIES:
            return "general"
        return normalized

    def _score_track(
        self,
        track: Track,
        weather_context: dict | None = None,
        user_history: dict | None = None,
    ) -> float:
        """
        Genera una puntuación heurística para un track.

        Usa una combinación ponderada de:
        - ajuste al contexto actual (default 0.6)
        - afinidad con el historial/preferencias del usuario (default 0.4)
        """
        user_history = user_history or {}
        audio_features = self._get_track_audio_features(track)

        energy = float(audio_features.get("energy", 0.5))
        danceability = float(audio_features.get("danceability", 0.5))
        valence = float(audio_features.get("valence", 0.5))
        acousticness = float(audio_features.get("acousticness", 0.3))
        popularity = float((track.popularity or 50) / 100.0)

        context_score = 0.0
        context_score += valence * 0.35
        context_score += energy * 0.25
        context_score += danceability * 0.25
        context_score += popularity * 0.15

        if weather_context:
            main = weather_context.get("main_status", "").lower()
            description = weather_context.get("description", "").lower()
            temperature = weather_context.get("temperature", 20)

            if any(
                x in main for x in ["rain", "drizzle", "thunderstorm", "snow", "cloud"]
            ):
                context_score += (1.0 - ((energy + danceability) / 2.0)) * 0.4
                context_score += acousticness * 0.2
            if any(x in main for x in ["clear", "sunny"]) or "sun" in description:
                context_score += (energy + valence) * 0.25
            if temperature <= 5:
                context_score += acousticness * 0.15
            elif temperature >= 25:
                context_score += danceability * 0.15

        history_score = 0.0
        avg_energy = float(user_history.get("avg_energy", 0.5))
        avg_danceability = float(user_history.get("avg_danceability", 0.5))
        avg_valence = float(user_history.get("avg_valence", 0.5))

        history_score += max(0.0, 1.0 - abs(energy - avg_energy)) * 0.25
        history_score += max(0.0, 1.0 - abs(danceability - avg_danceability)) * 0.25
        history_score += max(0.0, 1.0 - abs(valence - avg_valence)) * 0.25

        favorite_artists = set(user_history.get("favorite_artists", []))
        favorite_genres = set(user_history.get("favorite_genres", []))

        for artist in track.artists.all():
            if artist.name in favorite_artists:
                history_score += 0.35
            for genre in getattr(artist, "genres", []) or []:
                if genre.strip() in favorite_genres:
                    history_score += 0.15

        return (context_score * self.context_weight) + (
            history_score * self.history_weight
        )

    @staticmethod
    def _resolve_generation_mode(generation_meta: dict[str, bool]) -> str:
        online_signals = bool(generation_meta.get("used_spotify_sync")) or bool(
            generation_meta.get("used_spotify_catalog_fallback")
        )
        fallback_signals = bool(generation_meta.get("used_cached_news")) or bool(
            generation_meta.get("used_local_catalog")
        )

        if online_signals and fallback_signals:
            return "hybrid"
        if online_signals:
            return "online"
        return "fallback"

    def get_user_favorite_artists(self, user: User) -> list[str]:
        """Retorna los artistas favoritos del usuario."""
        return self._get_user_preferences(user)["artists"]

    def get_user_favorite_genres(self, user: User) -> list[str]:
        """Retorna los géneros favoritos del usuario."""
        return self._get_user_preferences(user)["genres"]

    def get_average_session_length(self, user: User) -> float:
        """Calcula la duración promedio de sesiones del usuario en segundos."""
        from apps.interactions.models import InteractionSession

        sessions = InteractionSession.objects.filter(user=user, ended_at__isnull=False)
        durations = [
            (session.ended_at - session.started_at).total_seconds()
            for session in sessions
            if session.ended_at
        ]
        if not durations:
            return 0.0
        return float(sum(durations) / len(durations))

    @staticmethod
    def _create_playlist(
        user: User, playlist_name: str, tracks: list[Track], session_id: str
    ) -> Playlist:
        """
        Crea una playlist en la BD.
        """
        playlist = Playlist.objects.create(
            user=user,
            name=playlist_name,
            spotify_id=f"moodsic_{session_id}",
            is_public=False,
        )

        # Añadir tracks a la playlist
        for idx, track in enumerate(tracks):
            PlaylistTrack.objects.create(
                playlist=playlist,
                track=track,
                order=idx,
            )

        return playlist

    @staticmethod
    def _sync_playlist_to_spotify(
        user: User, playlist: Playlist, tracks: list[Track]
    ) -> dict | None:
        """
        Sincroniza una playlist con Spotify usando la operación atómica del servicio.
        """
        try:
            spotify_service = SpotifyMusicService(user)
            track_uris = [t.uri for t in tracks if t.uri]

            if not track_uris:
                logger.warning("No track URIs available for Spotify sync.")
                return None

            return spotify_service.sync_playlist(
                name=playlist.name,
                description=f"Moodsic Playlist - {timezone.now().strftime('%Y-%m-%d')}",
                track_uris=track_uris,
                public=playlist.is_public,
            )
        except Exception as e:
            logger.error(
                f"Error synchronizing playlist with Spotify: {e}", exc_info=True
            )
            return None


# Instancia global
_service_instance = None


def get_playlist_generation_service() -> PlaylistGenerationService:
    """
    Obtiene la instancia global del servicio.
    """
    global _service_instance
    if _service_instance is None:
        _service_instance = PlaylistGenerationService()
    return _service_instance
