"""
Servicio de Generación de Playlists usando el Agente RL.
"""

import logging
import uuid
from collections import Counter
from typing import Dict, List, Optional, Tuple

import numpy as np
from django.contrib.auth import get_user_model
from django.db.models import Avg, Sum
from django.utils import timezone

from apps.context.models import WeatherContext
from apps.music.models import Track, Playlist, PlaylistTrack
from apps.music.services.spotify_music_service import SpotifyMusicService
from ml.agent import get_agent
from ml.reward import get_reward_calculator
from ml.state_builder import get_state_builder

logger = logging.getLogger(__name__)

User = get_user_model()


class PlaylistGenerationService:
    """
    Servicio para generar playlists inteligentes usando el agente RL.
    
    Coordina:
    1. Construcción del estado (contexto actual)
    2. Selección de tracks usando el agente
    3. Creación de playlist en Spotify
    4. Registro de la sesión para entrenamiento
    """

    def __init__(self):
        """Inicializa el servicio."""
        self.agent = get_agent()
        self.reward_calculator = get_reward_calculator()
        self.state_builder = get_state_builder()

    def generate_playlist(
        self,
        user: User,
        playlist_name: str = "Generated by Moodsic",
        count: int = 10,
        weather_context: Optional[Dict] = None,
        use_context: bool = True,
    ) -> Dict:
        """
        Genera una playlist personalizada para el usuario.
        
        Args:
            user: Usuario para el que generar la playlist
            playlist_name: Nombre de la playlist
            count: Número de canciones a incluir
            weather_context: Diccionario con contexto climático
            use_context: Si usar el contexto en la generación
            
        Returns:
            Dict con información de la playlist generada
        """
        logger.info(
            f"Generando playlist para usuario {user.username} "
            f"con {count} canciones"
        )

        try:
            # Crear sesión única
            session_id = str(uuid.uuid4())

            # Obtener tracks disponibles
            available_tracks = self._get_available_tracks(user)

            if len(available_tracks) == 0:
                raise ValueError("No hay canciones disponibles para generar playlist")

            # Limitar a tracks disponibles
            count = min(count, len(available_tracks))

            user_history = self._get_user_history(user)
            track_scores = self._score_tracks(
                available_tracks,
                weather_context=weather_context,
                user_history=user_history,
            )
            available_actions = sorted(
                list(range(len(available_tracks))),
                key=lambda idx: track_scores[idx],
                reverse=True,
            )

            # Construir estado inicial
            state = self.state_builder.build_state(
                user=user,
                weather_context=weather_context,
                current_track=None,
                time_of_day=self._get_time_of_day(),
            )

            # Seleccionar tracks usando el agente
            selected_track_indices = []

            for step in range(count):
                # El agente selecciona la mejor acción (track)
                action = self.agent.select_action(
                    state,
                    available_actions=available_actions,
                    training=False,  # Usar explotación pura
                )

                track_idx = action
                selected_track_indices.append(track_idx)

                # Remover track seleccionado para no repetir
                available_actions.remove(action)

                # Actualizar estado para siguiente iteración
                track = available_tracks[track_idx]
                track_features = self._get_track_audio_features(track)

                state = self.state_builder.build_state(
                    user=user,
                    weather_context=weather_context,
                    current_track=track_features,
                    time_of_day=self._get_time_of_day(),
                )

            # Crear playlist en BD
            selected_tracks = [available_tracks[idx] for idx in selected_track_indices]
            playlist = self._create_playlist(
                user=user,
                playlist_name=playlist_name,
                tracks=selected_tracks,
                session_id=session_id,
            )

            # Sincronizar con Spotify si el usuario está conectado
            if user.is_spotify_connected:
                try:
                    spotify_playlist = self._sync_playlist_to_spotify(
                        user=user,
                        playlist=playlist,
                        tracks=selected_tracks,
                    )
                    if spotify_playlist:
                        playlist.spotify_id = spotify_playlist.get("id", f"moodsic_{session_id}")
                        playlist.uri = spotify_playlist.get("uri", "")
                        playlist.save()
                        logger.info(
                            f"Playlist sincronizada con Spotify: {spotify_playlist.get('id')}"
                        )
                except Exception as e:
                    logger.warning(f"No se pudo sincronizar con Spotify: {e}")
                    # Continuar sin Spotify, playlist sigue siendo válida localmente

            logger.info(
                f"Playlist creada exitosamente: {playlist.id} "
                f"con {len(selected_tracks)} canciones"
            )

            return {
                "playlist_id": playlist.spotify_id,
                "playlist_name": playlist.name,
                "tracks_count": len(selected_tracks),
                "track_ids": [t.id for t in selected_tracks],
                "track_names": [t.name for t in selected_tracks],
                "estimated_duration": sum(t.duration_ms for t in selected_tracks)
                // 1000,
                "session_id": session_id,
                "created_at": timezone.now().isoformat(),
            }

        except Exception as e:
            logger.error(f"Error generando playlist: {e}", exc_info=True)
            raise

    def record_interaction(
        self,
        user: User,
        track: Track,
        feedback: str,
        play_duration: int,
        track_duration: int,
        session_id: str,
        weather_id: Optional[int] = None,
        news_ids: Optional[List[int]] = None,
    ) -> Dict:
        """
        Registra la interacción del usuario con un track.
        
        Args:
            user: Usuario
            track: Track reproducido
            feedback: Tipo de feedback
            play_duration: Segundos reproducidos
            track_duration: Duración total del track
            session_id: ID de la sesión
            weather_id: ID del contexto climático
            news_ids: IDs de noticias
            
        Returns:
            Dict con información de la interacción registrada
        """
        from apps.interactions.models import Interaction

        logger.info(
            f"Registrando interacción: {user.username} - {track.name} "
            f"({feedback})"
        )

        try:
            # Obtener contexto para calcular reward
            weather_context = None
            if weather_id:
                try:
                    weather = WeatherContext.objects.get(id=weather_id)
                    weather_context = {
                        "temperature": weather.temperature,
                        "humidity": weather.humidity,
                        "wind_speed": weather.wind_speed,
                        "main_status": weather.main_status,
                    }
                except WeatherContext.DoesNotExist:
                    pass

            # Obtener audio features del track
            audio_features = self._get_track_audio_features(track)

            # Obtener historico del usuario
            user_history = self._get_user_history(user)

            # Calcular reward
            reward = self.reward_calculator.calculate_reward(
                user_feedback=feedback,
                weather_context=weather_context,
                track_audio_features=audio_features,
                user_history=user_history,
            )
            reward = self.reward_calculator.normalize_reward(reward)

            # Guardar interacción
            interaction = Interaction.objects.create(
                user=user,
                track=track,
                feedback=feedback,
                play_duration=play_duration,
                track_duration=track_duration,
                reward=reward,
                weather_id=weather_id,
                news_ids=news_ids or [],
                session_id=session_id,
            )

            # Guardar la experiencia en el replay buffer del agente para entrenamient futuro
            state = self.state_builder.build_state(user, weather_context, audio_features)
            # Aquí iría la acción (track index) pero se omite para no complicar

            logger.info(f"Interacción guardada: {interaction.id}, Reward: {reward}")

            return {
                "interaction_id": interaction.id,
                "reward": reward,
                "completion_percentage": interaction.completion_percentage,
                "is_positive": interaction.is_positive,
            }

        except Exception as e:
            logger.error(f"Error registrando interacción: {e}", exc_info=True)
            raise

    def get_user_stats(self, user: User) -> Dict:
        """
        Obtiene estadísticas del usuario.
        """
        from apps.interactions.models import Interaction

        interactions = Interaction.objects.filter(user=user)
        total = interactions.count()

        if total == 0:
            return {
                "user_id": user.id,
                "total_interactions": 0,
                "total_skips": 0,
                "total_completed": 0,
                "average_reward": 0.0,
                "total_reward": 0.0,
                "skip_rate": 0.0,
                "completion_rate": 0.0,
                "favorite_genres": [],
                "favorite_artists": [],
                "average_session_length": 0.0,
            }

        skips = interactions.filter(feedback__startswith="skip").count()
        completed = interactions.filter(feedback="completed").count()
        avg_reward = interactions.aggregate(
            avg=Avg("reward")
        )["avg"] or 0.0
        total_reward = interactions.aggregate(
            total=Sum("reward")
        )["total"] or 0.0

        stats = {
            "user_id": user.id,
            "total_interactions": total,
            "total_skips": skips,
            "total_completed": completed,
            "average_reward": float(avg_reward),
            "total_reward": float(total_reward),
            "skip_rate": skips / total if total > 0 else 0.0,
            "completion_rate": completed / total if total > 0 else 0.0,
        }

        stats["favorite_genres"] = self.get_user_favorite_genres(user)
        stats["favorite_artists"] = self.get_user_favorite_artists(user)
        stats["average_session_length"] = self.get_average_session_length(user)
        return stats

    def _get_available_tracks(
        self, user: User, limit: int = 500
    ) -> List[Track]:
        """
        Obtiene tracks disponibles para seleccionar.
        
        Actualmente retorna todos los tracks. Puede filtrarse por:
        - Géneros preferidos del usuario
        - Popularidad
        - Recencia
        """
        max_tracks = min(limit, self.agent.action_dim)
        return list(
            Track.objects.prefetch_related("artists").all()[:max_tracks]
        )

    def _get_time_of_day(self) -> str:
        """Obtiene la hora del día actual."""
        hour = timezone.now().hour
        if 6 <= hour < 12:
            return "morning"
        elif 12 <= hour < 18:
            return "afternoon"
        elif 18 <= hour <= 23:
            return "evening"
        else:
            return "night"

    @staticmethod
    def _get_track_audio_features(track: Track) -> Dict:
        """
        Obtiene las características de audio de un track.
        """
        try:
            if hasattr(track, "audio_features"):
                af = track.audio_features
                return {
                    "energy": af.energy,
                    "danceability": af.danceability,
                    "valence": af.valence,
                    "acousticness": af.acousticness,
                    "instrumentalness": af.instrumentalness,
                    "liveness": af.liveness,
                    "loudness": af.loudness,
                    "tempo": af.tempo,
                    "speechiness": af.speechiness,
                    "key": af.key,
                    "mode": af.mode,
                    "time_signature": af.time_signature,
                }
        except Exception:
            pass

        # Retornar defaults si no existen
        return {
            "energy": 0.5,
            "danceability": 0.5,
            "valence": 0.5,
            "acousticness": 0.3,
            "instrumentalness": 0.0,
            "liveness": 0.2,
            "loudness": -5,
            "tempo": 120,
            "speechiness": 0.0,
            "key": 0,
            "mode": 1,
            "time_signature": 4,
        }

    def _get_user_history(self, user: User) -> Dict:
        """
        Obtiene el historico del usuario incluyendo preferencias.
        """
        from apps.interactions.models import Interaction

        interactions = Interaction.objects.filter(user=user).select_related(
            "track__audio_features"
        ).prefetch_related("track__artists")

        if interactions.count() == 0:
            return {
                "skip_rate": 0.3,
                "completion_rate": 0.7,
                "avg_energy": 0.5,
                "avg_danceability": 0.5,
                "avg_valence": 0.5,
                "favorite_artists": [],
                "favorite_genres": [],
            }

        skips = interactions.filter(feedback__startswith="skip").count()
        total = interactions.count()
        avg_energy = 0.0
        avg_danceability = 0.0
        avg_valence = 0.0
        feature_count = 0

        for interaction in interactions:
            audio_features = getattr(interaction.track, "audio_features", None)
            if audio_features:
                avg_energy += audio_features.energy
                avg_danceability += audio_features.danceability
                avg_valence += audio_features.valence
                feature_count += 1

        if feature_count > 0:
            avg_energy /= feature_count
            avg_danceability /= feature_count
            avg_valence /= feature_count
        else:
            avg_energy = 0.5
            avg_danceability = 0.5
            avg_valence = 0.5

        preferences = self._get_user_preferences(user)

        return {
            "skip_rate": skips / total if total > 0 else 0.0,
            "completion_rate": 1 - (skips / total if total > 0 else 0.0),
            "avg_energy": avg_energy,
            "avg_danceability": avg_danceability,
            "avg_valence": avg_valence,
            "favorite_artists": preferences["artists"],
            "favorite_genres": preferences["genres"],
        }

    def _get_user_preferences(self, user: User) -> Dict[str, List[str]]:
        """
        Retorna los artistas y géneros más frecuentes en el historial del usuario.
        """
        from apps.interactions.models import Interaction

        interactions = Interaction.objects.filter(user=user).select_related(
            "track__audio_features"
        ).prefetch_related("track__artists")

        artist_counter = Counter()
        genre_counter = Counter()

        for interaction in interactions:
            for artist in interaction.track.artists.all():
                artist_counter[artist.name] += 1
                for genre in getattr(artist, "genres", []) or []:
                    normalized = genre.strip()
                    if normalized:
                        genre_counter[normalized] += 1

        return {
            "artists": [name for name, _ in artist_counter.most_common(5)],
            "genres": [name for name, _ in genre_counter.most_common(5)],
        }

    def _score_tracks(
        self,
        tracks: List[Track],
        weather_context: Optional[Dict] = None,
        user_history: Optional[Dict] = None,
    ) -> List[float]:
        """
        Calcula una puntuación para cada track basada en clima e historial.
        """
        user_history = user_history or {}
        return [
            self._score_track(track, weather_context, user_history)
            for track in tracks
        ]

    def _score_track(
        self,
        track: Track,
        weather_context: Optional[Dict] = None,
        user_history: Optional[Dict] = None,
    ) -> float:
        """
        Genera una puntuación heurística para un track.
        """
        user_history = user_history or {}
        audio_features = self._get_track_audio_features(track)
        score = 0.0

        energy = audio_features.get("energy", 0.5)
        danceability = audio_features.get("danceability", 0.5)
        valence = audio_features.get("valence", 0.5)
        acousticness = audio_features.get("acousticness", 0.3)
        popularity = (track.popularity or 50) / 100.0

        score += valence * 0.3
        score += energy * 0.2
        score += danceability * 0.2
        score += popularity * 0.1

        if weather_context:
            main = weather_context.get("main_status", "").lower()
            description = weather_context.get("description", "").lower()
            temperature = weather_context.get("temperature", 20)

            if any(x in main for x in ["rain", "drizzle", "thunderstorm", "snow", "cloud"]):
                score += (1.0 - ((energy + danceability) / 2.0)) * 0.4
                score += acousticness * 0.2
            if any(x in main for x in ["clear", "sunny"]) or "sun" in description:
                score += (energy + valence) * 0.25
            if temperature <= 5:
                score += acousticness * 0.15
            elif temperature >= 25:
                score += danceability * 0.15

        favorite_artists = set(user_history.get("favorite_artists", []))
        favorite_genres = set(user_history.get("favorite_genres", []))

        for artist in track.artists.all():
            if artist.name in favorite_artists:
                score += 1.0
            for genre in getattr(artist, "genres", []) or []:
                if genre.strip() in favorite_genres:
                    score += 0.5

        return score

    def get_user_favorite_artists(self, user: User) -> List[str]:
        """Retorna los artistas favoritos del usuario."""
        return self._get_user_preferences(user)["artists"]

    def get_user_favorite_genres(self, user: User) -> List[str]:
        """Retorna los géneros favoritos del usuario."""
        return self._get_user_preferences(user)["genres"]

    def get_average_session_length(self, user: User) -> float:
        """Calcula la duración promedio de sesiones del usuario en segundos."""
        from apps.interactions.models import InteractionSession

        sessions = InteractionSession.objects.filter(user=user, ended_at__isnull=False)
        durations = [
            (session.ended_at - session.started_at).total_seconds()
            for session in sessions
            if session.ended_at
        ]
        if not durations:
            return 0.0
        return float(sum(durations) / len(durations))

    @staticmethod
    def _create_playlist(
        user: User, playlist_name: str, tracks: List[Track], session_id: str
    ) -> Playlist:
        """
        Crea una playlist en la BD.
        """
        playlist = Playlist.objects.create(
            user=user,
            name=playlist_name,
            spotify_id=f"moodsic_{session_id}",
            is_public=False,
        )

        # Añadir tracks a la playlist
        for idx, track in enumerate(tracks):
            PlaylistTrack.objects.create(
                playlist=playlist,
                track=track,
                order=idx,
            )

        return playlist

    @staticmethod
    def _sync_playlist_to_spotify(
        user: User, playlist: Playlist, tracks: List[Track]
    ) -> Optional[Dict]:
        """
        Sincroniza una playlist con Spotify, creándola y agregando tracks.
        
        Args:
            user: Usuario (debe estar conectado a Spotify)
            playlist: Objeto de playlist de Django
            tracks: Lista de Track objects
            
        Returns:
            Diccionario con información de la playlist de Spotify, o None
        """
        try:
            spotify_service = SpotifyMusicService(user)
            if not spotify_service.client:
                logger.warning(f"Usuario {user.username} no tiene cliente Spotify disponible")
                return None

            # 1. Crear la playlist en Spotify
            logger.info(f"Creando playlist en Spotify: {playlist.name}")
            spotify_playlist = spotify_service.create_playlist(
                name=playlist.name,
                description=f"Generated by Moodsic on {timezone.now().strftime('%Y-%m-%d %H:%M')}",
                public=playlist.is_public,
            )

            if not spotify_playlist:
                logger.error("No se pudo crear playlist en Spotify")
                return None

            playlist_id = spotify_playlist.get("id")
            logger.info(f"Playlist creada en Spotify: {playlist_id}")

            # 2. Obtener URIs de los tracks
            track_uris = [t.uri for t in tracks if t.uri]
            
            if not track_uris:
                logger.warning("No hay URIs de tracks disponibles para agregar a Spotify")
                return spotify_playlist

            # 3. Agregar tracks a la playlist
            logger.info(f"Agregando {len(track_uris)} tracks a playlist {playlist_id}")
            success = spotify_service.add_tracks_to_playlist(playlist_id, track_uris)

            if success:
                logger.info(f"Tracks agregados exitosamente a playlist {playlist_id}")
            else:
                logger.warning(f"Hubo problemas agregando tracks a playlist {playlist_id}")

            return spotify_playlist

        except Exception as e:
            logger.error(f"Error sincronizando playlist con Spotify: {e}", exc_info=True)
            return None


# Instancia global
_service_instance = None


def get_playlist_generation_service() -> PlaylistGenerationService:
    """
    Obtiene la instancia global del servicio.
    """
    global _service_instance
    if _service_instance is None:
        _service_instance = PlaylistGenerationService()
    return _service_instance
