"""
API Endpoints para Playlist Generation usando Django-Ninja.
"""

import logging

from django.contrib.auth import get_user_model
from ninja import Router
from ninja.responses import Response

from apps.context.models import WeatherContext
from apps.interactions.schemas import (
    PlaylistGenerateResponseSchema,
    PlaylistGenerateSchema,
)
from apps.interactions.services.playlist_generation_service import (
    get_playlist_generation_service,
)
from apps.music.models import Album, Artist, Playlist, Track, TrackAudioFeatures
from apps.music.services.spotify_music_service import SpotifyMusicService

logger = logging.getLogger(__name__)

router = Router()
User = get_user_model()
MAX_PLAYLIST_TRACKS = 100


@router.post(
    "/playlists/generate/",
    response=PlaylistGenerateResponseSchema,
    tags=["playlists"],
)
def generate_playlist(request, payload: PlaylistGenerateSchema):
    """
    Genera una playlist personalizada usando el agente RL.

    El sistema analiza el contexto actual (clima, hora, noticias)
    y selecciona canciones óptimas basadas en preferencias del usuario
    y feedback histórico.

    **Campos:**
    - name: Nombre de la playlist (default: "Generated by Moodsic")
    - count: Número de canciones (default: 10, max: 100)
    - weather_id: ID del contexto climático a usar (opcional)
    - use_context: Si usar contexto en la generación (default: True)

    **Retorna:** PlaylistGenerateResponseSchema con:
    - playlist_id: ID de la playlist creada
    - playlist_name: Nombre de la playlist
    - tracks_count: Número de canciones
    - track_ids: IDs de los tracks
    - track_names: Nombres de los tracks
    - estimated_duration: Duración estimada en segundos
    - created_at: Timestamp de creación

    **Ejemplo:**
    ```json
    {
        "name": "My Workout Mix",
        "count": 20,
        "use_context": true
    }
    ```
    """
    if not request.user.is_authenticated:
        return Response(
            {
                "error": "Autenticación requerida",
                "message": "Inicia sesión para generar una playlist personalizada.",
            },
            status=401,
        )

    try:
        requested_count = payload.count
        count = min(payload.count, MAX_PLAYLIST_TRACKS)
        warnings = []
        if requested_count > MAX_PLAYLIST_TRACKS:
            warnings.append(
                "La petición superaba el máximo permitido; la playlist se ha limitado a 100 canciones."
            )

        weather_context = None
        if payload.use_context and payload.weather_id:
            try:
                weather = WeatherContext.objects.get(id=payload.weather_id)
                base_temperature = (
                    weather.temperature if weather.temperature is not None else 20
                )
                weather_context = {
                    "temperature": base_temperature,
                    "feels_like": (
                        weather.feels_like
                        if weather.feels_like is not None
                        else base_temperature
                    ),
                    "humidity": weather.humidity if weather.humidity is not None else 60,
                    "wind_speed": weather.wind_speed if weather.wind_speed is not None else 0,
                    "pressure": weather.pressure if weather.pressure is not None else 1013,
                    "visibility": weather.visibility if weather.visibility is not None else 10000,
                    "clouds_all": weather.clouds_all if weather.clouds_all is not None else 50,
                    "rain_probability": weather.rain_1h if weather.rain_1h is not None else 0,
                    "main_status": weather.main_status,
                    "description": weather.description,
                    "timestamp": weather.timestamp.isoformat(),
                }
            except WeatherContext.DoesNotExist:
                return Response(
                    {
                        "error": "Weather context no encontrado",
                        "message": "El identificador de clima enviado no existe o ya no está disponible.",
                    },
                    status=404,
                )

        service = get_playlist_generation_service()

        result = service.generate_playlist(
            user=request.user,
            playlist_name=payload.name,
            count=count,
            weather_context=weather_context,
            use_context=payload.use_context,
            news_category=payload.news_category,
            news_query=payload.news_query,
            news_limit=payload.news_limit,
        )
        result["message"] = (
            f"Playlist generada correctamente en modo {result['mode']} con "
            f"{result['tracks_count']} canciones."
        )
        result["warnings"] = warnings

        logger.info("Playlist generada para %s", request.user.username)
        return result

    except ValueError as exc:
        logger.warning("No se pudo generar la playlist: %s", exc)
        return Response(
            {
                "error": "No se pudo generar la playlist",
                "message": str(exc),
            },
            status=400,
        )
    except Exception as exc:
        logger.error("Error generando playlist: %s", exc, exc_info=True)
        return Response(
            {
                "error": "Error interno generando la playlist",
                "message": "Se ha conservado el modo seguro. Reinténtalo en unos segundos.",
            },
            status=500,
        )


@router.get(
    "/playlists/",
    tags=["playlists"],
)
def list_user_playlists(request):
    """
    Lista todas las playlists del usuario autenticado.

    **Retorna:** Lista de playlists con:
    - playlist_id: ID de la playlist
    - playlist_name: Nombre
    - tracks_count: Número de tracks
    - created_at: Fecha de creación
    - spotify_url: URL de Spotify si está sincronizada
    """
    if not request.user.is_authenticated:
        return Response(
            {
                "error": "Autenticación requerida",
                "message": "Inicia sesión para consultar tus playlists guardadas.",
            },
            status=401,
        )

    try:
        playlists = Playlist.objects.filter(user=request.user).order_by("-created_at")

        result = []
        for playlist in playlists:
            tracks = playlist.tracks.all()
            result.append({
                "playlist_id": playlist.spotify_id,
                "playlist_name": playlist.name,
                "user_id": playlist.user_id,
                "tracks_count": tracks.count(),
                "is_public": playlist.is_public,
                "estimated_duration": sum(t.duration_ms for t in tracks) // 1000,
                "created_at": playlist.created_at.isoformat(),
                "spotify_uri": playlist.uri,
            })

        return {"playlists": result, "total": len(result)}

    except Exception as e:
        logger.error(f"Error listando playlists: {e}")
        return Response(
            {
                "error": "Error listando playlists",
                "message": "No se pudieron recuperar las playlists del usuario.",
            },
            status=500,
        )


@router.get(
    "/playlists/{playlist_id}/",
    tags=["playlists"],
)
def get_playlist_details(request, playlist_id: str):
    """
    Obtiene detalles de una playlist generada.

    **Parámetros:**
    - playlist_id: ID de la playlist

    **Retorna:** Información detallada de la playlist
    """
    if not request.user.is_authenticated:
        return Response(
            {
                "error": "Autenticación requerida",
                "message": "Inicia sesión para consultar el detalle de la playlist.",
            },
            status=401,
        )

    try:
        playlist = Playlist.objects.get(spotify_id=playlist_id, user=request.user)

        tracks = playlist.tracks.all()

        return {
            "playlist_id": playlist.spotify_id,
            "playlist_name": playlist.name,
            "user_id": playlist.user_id,
            "tracks_count": tracks.count(),
            "track_ids": [t.id for t in tracks],
            "track_names": [t.name for t in tracks],
            "track_artists": [", ".join([a.name for a in t.artists.all()]) for t in tracks],
            "estimated_duration": sum(t.duration_ms for t in tracks) // 1000,
            "is_public": playlist.is_public,
            "created_at": playlist.created_at.isoformat(),
            "updated_at": playlist.updated_at.isoformat(),
            "spotify_uri": playlist.uri,
        }

    except Exception as e:
        logger.error(f"Error obteniendo playlist: {e}")
        return Response(
            {
                "error": "Playlist no encontrada",
                "message": "No existe una playlist con ese identificador para el usuario autenticado.",
            },
            status=404,
        )


@router.post(
    "/playlists/{playlist_id}/sync-spotify/",
    tags=["playlists"],
)
@router.post(
    "/playlists/{playlist_id}/sync-spotify/",
    tags=["playlists"],
)
def sync_playlist_to_spotify(request, playlist_id: str):
    """
    Sincroniza una playlist generada localmente con la cuenta real de Spotify del usuario.
    """
    try:
        # 1. Usamos el usuario actual autenticado en la petición (ej. martinmiguelanez)
        target_user = request.user

        # --- PRINT DE DEPURACIÓN ---
        print("\n--- DEBUG SYNC ---")
        print(f"Usuario detectado: {target_user}")
        print(f"ID del usuario: {target_user.id}")
        print(f"¿Está autenticado?: {target_user.is_authenticated}")
        print("------------------\n")

        # 2. Verificación de seguridad: Comprobamos si el usuario tiene tokens
        # Se verifica tanto el campo is_spotify_connected como la existencia del token
        if not hasattr(target_user, "access_token") or not target_user.access_token:
            return Response(
                {
                    "success": False,
                    "error": "Usuario no está conectado a Spotify",
                    "message": f"El usuario {target_user.username} no tiene tokens de acceso en la base de datos.",
                },
                status=403,
            )

        # 3. Obtener la playlist local generada previamente
        # Filtramos por user para asegurar que nadie sincronice playlists de otros
        playlist = Playlist.objects.get(spotify_id=playlist_id, user=target_user)
        tracks = playlist.tracks.all()

        if not tracks.exists():
            return Response(
                {
                    "success": False,
                    "error": "Playlist vacía",
                    "message": "La playlist seleccionada no contiene canciones para sincronizar.",
                },
                status=400,
            )

        # 4. Inicializar el servicio de Spotify con los tokens del usuario actual
        spotify_service = SpotifyMusicService(target_user)

        # 5. Crear la playlist física en la cuenta de Spotify
        spotify_playlist = spotify_service.create_playlist(
            name=playlist.name,
            description="Generada por Moodsic AI",
            public=playlist.is_public,
        )

        if not spotify_playlist:
            return Response(
                {"success": False, "error": "Error al crear la playlist en los servidores de Spotify"},
                status=500
            )

        # 6. Extraer URIs de las canciones y agregarlas a la playlist creada
        track_uris = [t.uri for t in tracks if t.uri]
        if track_uris:
            spotify_service.add_tracks_to_playlist(spotify_playlist.get("id"), track_uris)

        # 7. Actualizar la playlist local con el URI de Spotify (opcional, para referencia futura)
        playlist.uri = spotify_playlist.get("uri")
        playlist.save()

        return {
            "success": True,
            "spotify_id": spotify_playlist.get("id"),
            "external_url": spotify_playlist.get("external_urls", {}).get("spotify", ""),
            "tracks_added": len(track_uris),
            "message": f"¡Éxito! Se han añadido {len(track_uris)} canciones a tu Spotify."
        }

    except Playlist.DoesNotExist:
        return Response(
            {
                "error": "Playlist local no encontrada",
                "message": f"No se encontró la playlist con ID {playlist_id} para este usuario."
            },
            status=404
        )
    except Exception as e:
        logger.error(f"Error en sync_playlist_to_spotify: {e!s}", exc_info=True)
        return Response({"error": "Error interno del servidor", "detail": str(e)}, status=500)


@router.post(
    "/tracks/sync/",
    tags=["tracks"],
)
def sync_tracks_from_spotify(  # noqa: C901, PLR0912
    request,
    source: str = "liked",
    limit: int = 50,
    save_audio_features: bool = False,
):
    """
    Sincroniza tracks desde Spotify con la BD local.

    **Parámetros:**
    - source: Fuente de tracks ('liked', 'top', 'playlist')
    - limit: Número máximo de tracks (default: 50)
    - save_audio_features: Guardar características de audio

    **Retorna:**
    - success: True si fue exitoso
    - synced_count: Número de tracks nuevos sincronizados
    - skipped_count: Tracks que ya existían
    - total_processed: Total procesados
    """

    try:
        # Verificar que el usuario está conectado a Spotify
        if not request.user.is_spotify_connected:
            return Response(
                {"success": False, "error": "Usuario no está conectado a Spotify"},
                status=403,
            )

        # Inicializar servicio
        spotify_service = SpotifyMusicService(request.user)
        if not spotify_service.client:
            return Response(
                {"success": False, "error": "No se pudo autenticar con Spotify"},
                status=500,
            )

        # Obtener tracks según la fuente
        if source == "liked":
            tracks_data = spotify_service.get_user_liked_tracks(limit=limit)
        elif source == "top":
            tracks_data = spotify_service.get_top_tracks(limit=limit)
        else:
            return Response(
                {"success": False, "error": f"Fuente no reconocida: {source}"},
                status=400,
            )

        if not tracks_data:
            return {
                "success": True,
                "synced_count": 0,
                "skipped_count": 0,
                "total_processed": 0,
                "message": "No se encontraron tracks"
            }

        # Guardar tracks
        saved_count = 0
        skipped_count = 0
        artist_cache = {}
        audio_features_data = {}

        # Obtener audio features si se solicita
        if save_audio_features:
            track_ids = [t.get("id") for t in tracks_data if t.get("id")]
            if track_ids:
                audio_features_data = spotify_service.get_audio_features(track_ids)

        for track_data in tracks_data:
            try:
                # Obtener o crear album
                if track_data.get("album_id"):
                    album, _ = Album.objects.get_or_create(
                        spotify_id=track_data.get("album_id"),
                        defaults={
                            "name": track_data.get("album", "Unknown"),
                            "album_type": "",
                        },
                    )
                else:
                    album = None

                # Obtener o crear artistas
                artists = []
                for artist_name in track_data.get("artists", []):
                    artist_key = artist_name.lower()
                    if artist_key not in artist_cache:
                        artist, _ = Artist.objects.get_or_create(
                            name=artist_name,
                            defaults={"spotify_id": f"local_{artist_key}"},
                        )
                        artist_cache[artist_key] = artist
                    artists.append(artist_cache[artist_key])

                # Obtener o crear track
                track, created = Track.objects.get_or_create(
                    spotify_id=track_data.get("id", ""),
                    defaults={
                        "name": track_data.get("name", "Unknown"),
                        "album": album,
                        "duration_ms": track_data.get("duration_ms", 0),
                        "explicit": track_data.get("explicit", False),
                        "popularity": track_data.get("popularity", 0),
                        "preview_url": track_data.get("preview_url", ""),
                        "uri": track_data.get("uri", ""),
                        "track_number": 0,
                    },
                )

                if artists:
                    track.artists.add(*artists)

                if created:
                    saved_count += 1

                    # Guardar audio features si están disponibles
                    if save_audio_features and track_data.get("id") in audio_features_data:
                        try:
                            TrackAudioFeatures.objects.get_or_create(
                                track=track,
                                defaults=audio_features_data[track_data.get("id")]
                            )
                        except Exception as e:
                            logger.warning(f"Error saving audio features: {e}")
                else:
                    skipped_count += 1

            except Exception as e:
                logger.error(f"Error procesando track: {e}")
                continue

        logger.info(f"Sincronización completada: {saved_count} nuevos, {skipped_count} existentes")

        return {
            "success": True,
            "synced_count": saved_count,
            "skipped_count": skipped_count,
            "total_processed": len(tracks_data),
            "source": source,
            "message": f"Sincronización completada: {saved_count} nuevos tracks"
        }

    except Exception as e:
        logger.error(f"Error sincronizando tracks: {e}", exc_info=True)
        return Response({"success": False, "error": str(e)}, status=500)
