"""
API Endpoints para Playlist Generation usando Django-Ninja.
"""

import logging

from ninja import Router
from ninja.responses import Response
from django.contrib.auth import get_user_model

from apps.interactions.schemas import (
    PlaylistGenerateSchema,
    PlaylistGenerateResponseSchema,
)
from apps.interactions.services.playlist_generation_service import (
    get_playlist_generation_service,
)
from apps.music.services.spotify_music_service import SpotifyMusicService

logger = logging.getLogger(__name__)

router = Router()
User = get_user_model()


@router.post(
    "/playlists/generate/",
    response=PlaylistGenerateResponseSchema,
    tags=["playlists"],
)
def generate_playlist(request, payload: PlaylistGenerateSchema):
    """
    Genera una playlist personalizada usando el agente RL.
    
    El sistema analiza el contexto actual (clima, hora, noticias)
    y selecciona canciones óptimas basadas en preferencias del usuario
    y feedback histórico.
    
    **Campos:**
    - name: Nombre de la playlist (default: "Generated by Moodsic")
    - count: Número de canciones (default: 10, max: 100)
    - weather_id: ID del contexto climático a usar (opcional)
    - use_context: Si usar contexto en la generación (default: True)
    
    **Retorna:** PlaylistGenerateResponseSchema con:
    - playlist_id: ID de la playlist creada
    - playlist_name: Nombre de la playlist
    - tracks_count: Número de canciones
    - track_ids: IDs de los tracks
    - track_names: Nombres de los tracks
    - estimated_duration: Duración estimada en segundos
    - created_at: Timestamp de creación
    
    **Ejemplo:**
    ```json
    {
        "name": "My Workout Mix",
        "count": 20,
        "use_context": true
    }
    ```
    """
    try:
        # Limitar cantidad máxima de canciones
        count = min(payload.count, 100)

        weather_context = None
        if payload.use_context and payload.weather_id:
            from apps.context.models import WeatherContext

            try:
                weather = WeatherContext.objects.get(id=payload.weather_id)
                weather_context = {
                    "temperature": weather.temperature if weather.temperature is not None else 20,
                    "feels_like": weather.feels_like if weather.feels_like is not None else weather.temperature if weather.temperature is not None else 20,
                    "humidity": weather.humidity if weather.humidity is not None else 60,
                    "wind_speed": weather.wind_speed if weather.wind_speed is not None else 0,
                    "pressure": weather.pressure if weather.pressure is not None else 1013,
                    "visibility": weather.visibility if weather.visibility is not None else 10000,
                    "clouds_all": weather.clouds_all if weather.clouds_all is not None else 50,
                    "rain_probability": weather.rain_1h if weather.rain_1h is not None else 0,
                    "main_status": weather.main_status,
                    "description": weather.description,
                    "timestamp": weather.timestamp.isoformat(),
                }
            except WeatherContext.DoesNotExist:
                return Response({"error": "Weather context no encontrado"}, status=404)

        service = get_playlist_generation_service()

        result = service.generate_playlist(
            user=request.user,
            playlist_name=payload.name,
            count=count,
            weather_context=weather_context,
            use_context=payload.use_context,
        )

        logger.info(f"Playlist generada para {request.user.username}")

        return result

    except Exception as e:
        logger.error(f"Error generando playlist: {e}", exc_info=True)
        return Response({"error": str(e)}, status=500)


@router.get(
    "/playlists/",
    tags=["playlists"],
)
def list_user_playlists(request):
    """
    Lista todas las playlists del usuario autenticado.
    
    **Retorna:** Lista de playlists con:
    - playlist_id: ID de la playlist
    - playlist_name: Nombre
    - tracks_count: Número de tracks
    - created_at: Fecha de creación
    - spotify_url: URL de Spotify si está sincronizada
    """
    from apps.music.models import Playlist

    try:
        playlists = Playlist.objects.filter(user=request.user).order_by("-created_at")
        
        result = []
        for playlist in playlists:
            tracks = playlist.tracks.all()
            result.append({
                "playlist_id": playlist.spotify_id,
                "playlist_name": playlist.name,
                "user_id": playlist.user_id,
                "tracks_count": tracks.count(),
                "is_public": playlist.is_public,
                "estimated_duration": sum(t.duration_ms for t in tracks) // 1000,
                "created_at": playlist.created_at.isoformat(),
                "spotify_uri": playlist.uri,
            })

        return {"playlists": result, "total": len(result)}

    except Exception as e:
        logger.error(f"Error listando playlists: {e}")
        return {"error": "Error listando playlists"}, 500


@router.get(
    "/playlists/{playlist_id}/",
    tags=["playlists"],
)
def get_playlist_details(request, playlist_id: str):
    """
    Obtiene detalles de una playlist generada.
    
    **Parámetros:**
    - playlist_id: ID de la playlist
    
    **Retorna:** Información detallada de la playlist
    """
    from apps.music.models import Playlist

    try:
        playlist = Playlist.objects.get(spotify_id=playlist_id, user=request.user)

        tracks = playlist.tracks.all()

        return {
            "playlist_id": playlist.spotify_id,
            "playlist_name": playlist.name,
            "user_id": playlist.user_id,
            "tracks_count": tracks.count(),
            "track_ids": [t.id for t in tracks],
            "track_names": [t.name for t in tracks],
            "track_artists": [", ".join([a.name for a in t.artists.all()]) for t in tracks],
            "estimated_duration": sum(t.duration_ms for t in tracks) // 1000,
            "is_public": playlist.is_public,
            "created_at": playlist.created_at.isoformat(),
            "updated_at": playlist.updated_at.isoformat(),
            "spotify_uri": playlist.uri,
        }

    except Exception as e:
        logger.error(f"Error obteniendo playlist: {e}")
        return {"error": "Playlist no encontrada"}, 404


@router.post(
    "/playlists/{playlist_id}/sync-spotify/",
    tags=["playlists"],
)
def sync_playlist_to_spotify(request, playlist_id: str):
    """
    Sincroniza una playlist local con Spotify.
    
    Crea la playlist en Spotify y agrega todos los tracks.
    
    **Parámetros:**
    - playlist_id: ID de la playlist local
    
    **Retorna:**
    - success: True si fue exitoso
    - spotify_id: ID de la playlist creada en Spotify
    - spotify_uri: URI de Spotify
    - message: Mensaje de estado
    """
    from apps.music.models import Playlist

    try:
        # Verificar que el usuario está conectado a Spotify
        if not request.user.is_spotify_connected:
            return {
                "success": False,
                "error": "Usuario no está conectado a Spotify",
                "message": "Conecta tu cuenta de Spotify en settings"
            }, 403

        # Obtener playlist
        playlist = Playlist.objects.get(spotify_id=playlist_id, user=request.user)
        tracks = playlist.tracks.all()

        # Inicializar servicio de Spotify
        spotify_service = SpotifyMusicService(request.user)
        if not spotify_service.client:
            return {
                "success": False,
                "error": "No se pudo autenticar con Spotify"
            }, 500

        # Crear playlist en Spotify
        spotify_playlist = spotify_service.create_playlist(
            name=playlist.name,
            description=f"Generated by Moodsic",
            public=playlist.is_public,
        )

        if not spotify_playlist:
            return {
                "success": False,
                "error": "No se pudo crear playlist en Spotify"
            }, 500

        # Agregar tracks
        track_uris = [t.uri for t in tracks if t.uri]
        if track_uris:
            success = spotify_service.add_tracks_to_playlist(
                spotify_playlist.get("id"),
                track_uris
            )
            if not success:
                logger.warning(f"Algunos tracks no se agregaron a {spotify_playlist.get('id')}")

        # Actualizar registro en BD
        playlist.spotify_id = spotify_playlist.get("id", playlist_id)
        playlist.uri = spotify_playlist.get("uri", "")
        playlist.save()

        logger.info(f"Playlist sincronizada: {spotify_playlist.get('id')}")

        return {
            "success": True,
            "spotify_id": spotify_playlist.get("id"),
            "spotify_uri": spotify_playlist.get("uri"),
            "external_url": spotify_playlist.get("external_urls", {}).get("spotify", ""),
            "tracks_added": len(track_uris)
        }

    except Playlist.DoesNotExist:
        return {"error": "Playlist no encontrada"}, 404
    except Exception as e:
        logger.error(f"Error sincronizando playlist con Spotify: {e}", exc_info=True)
        return {"error": str(e)}, 500


@router.post(
    "/tracks/sync/",
    tags=["tracks"],
)
def sync_tracks_from_spotify(request, source: str = "liked", limit: int = 50, 
                             save_audio_features: bool = False):
    """
    Sincroniza tracks desde Spotify con la BD local.
    
    **Parámetros:**
    - source: Fuente de tracks ('liked', 'top', 'playlist')
    - limit: Número máximo de tracks (default: 50)
    - save_audio_features: Guardar características de audio
    
    **Retorna:**
    - success: True si fue exitoso
    - synced_count: Número de tracks nuevos sincronizados
    - skipped_count: Tracks que ya existían
    - total_processed: Total procesados
    """
    from apps.music.models import Track, Album, Artist, TrackAudioFeatures

    try:
        # Verificar que el usuario está conectado a Spotify
        if not request.user.is_spotify_connected:
            return {
                "success": False,
                "error": "Usuario no está conectado a Spotify"
            }, 403

        # Inicializar servicio
        spotify_service = SpotifyMusicService(request.user)
        if not spotify_service.client:
            return {
                "success": False,
                "error": "No se pudo autenticar con Spotify"
            }, 500

        # Obtener tracks según la fuente
        if source == "liked":
            tracks_data = spotify_service.get_user_liked_tracks(limit=limit)
        elif source == "top":
            tracks_data = spotify_service.get_top_tracks(limit=limit)
        else:
            return {
                "success": False,
                "error": f"Fuente no reconocida: {source}"
            }, 400

        if not tracks_data:
            return {
                "success": True,
                "synced_count": 0,
                "skipped_count": 0,
                "total_processed": 0,
                "message": "No se encontraron tracks"
            }

        # Guardar tracks
        saved_count = 0
        skipped_count = 0
        artist_cache = {}
        audio_features_data = {}

        # Obtener audio features si se solicita
        if save_audio_features:
            track_ids = [t.get("id") for t in tracks_data if t.get("id")]
            if track_ids:
                audio_features_data = spotify_service.get_audio_features(track_ids)

        for track_data in tracks_data:
            try:
                # Obtener o crear album
                if track_data.get("album_id"):
                    album, _ = Album.objects.get_or_create(
                        spotify_id=track_data.get("album_id"),
                        defaults={
                            "name": track_data.get("album", "Unknown"),
                            "album_type": "",
                        },
                    )
                else:
                    album = None

                # Obtener o crear artistas
                artists = []
                for artist_name in track_data.get("artists", []):
                    artist_key = artist_name.lower()
                    if artist_key not in artist_cache:
                        artist, _ = Artist.objects.get_or_create(
                            name=artist_name,
                            defaults={"spotify_id": f"local_{artist_key}"},
                        )
                        artist_cache[artist_key] = artist
                    artists.append(artist_cache[artist_key])

                # Obtener o crear track
                track, created = Track.objects.get_or_create(
                    spotify_id=track_data.get("id", ""),
                    defaults={
                        "name": track_data.get("name", "Unknown"),
                        "album": album,
                        "duration_ms": track_data.get("duration_ms", 0),
                        "explicit": track_data.get("explicit", False),
                        "popularity": track_data.get("popularity", 0),
                        "preview_url": track_data.get("preview_url", ""),
                        "uri": track_data.get("uri", ""),
                        "track_number": 0,
                    },
                )

                if artists:
                    track.artists.add(*artists)

                if created:
                    saved_count += 1
                    
                    # Guardar audio features si están disponibles
                    if save_audio_features and track_data.get("id") in audio_features_data:
                        try:
                            TrackAudioFeatures.objects.get_or_create(
                                track=track,
                                defaults=audio_features_data[track_data.get("id")]
                            )
                        except Exception as e:
                            logger.warning(f"Error saving audio features: {e}")
                else:
                    skipped_count += 1

            except Exception as e:
                logger.error(f"Error procesando track: {e}")
                continue

        logger.info(f"Sincronización completada: {saved_count} nuevos, {skipped_count} existentes")

        return {
            "success": True,
            "synced_count": saved_count,
            "skipped_count": skipped_count,
            "total_processed": len(tracks_data),
            "source": source,
            "message": f"Sincronización completada: {saved_count} nuevos tracks"
        }

    except Exception as e:
        logger.error(f"Error sincronizando tracks: {e}", exc_info=True)
        return {"success": False, "error": str(e)}, 500
