# Generated by Django 4.2.30 on 2026-04-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_spotify_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_token",
            field=models.TextField(
                blank=True,
                help_text="Token de acceso para llamadas a la API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="refresh_token",
            field=models.TextField(
                blank=True,
                help_text="Token para refrescar la sesión sin pedir login al usuario",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="token_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento exacto en el que el access_token deja de ser válido",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL de la imagen de perfil de Spotify",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_spotify_connected",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario ha completado el flujo de OAuth exitosamente",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="spotify_id",
            field=models.CharField(
                blank=True,
                help_text="ID único proporcionado por la API de Spotify",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
