# Generated by Django 6.0.4 on 2026-05-04 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0015_alter_city_search_names"),
        ("users", "0005_user_access_token_user_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="Ciudad preferida o actual del usuario para personalizar el contexto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cities_light.city",
            ),
        ),
    ]
